Backend Filters Data API
TUMFARSynchrony/experimental-hub pull request #161
Opened 2023-10-12 19:09 UTC by tobifb

This PR adds two new API calls. With those API calls, data from filters can be fetched.

## GET_FILTERS_DATA

### Description

Get all data for requested filter for all participants or only specific (if request is made from Participant). Server will respond with all data of filter that match filter name, channel and id.
BE CAUTIOUS: call from participant does not work (look at issues)

### Request

| Type   | Data                             |
| ------ | -------------------------------- |
| `GET_FILTERS_DATA` | [GetFiltersDataRequest](./Data-Types#getfiltersdatarequest) JSON |

### Response

| Type    | Data                           |
| ------- | ------------------------------ |
| `FILTERS_DATA` | dict of \[str, [FiltersData](./Data-Types#filtersdata)\] JSON |

<br>

## GET_FILTERS_TEST_STATUS

### Description

Get all test status for requested filter for all participants or only specific. Server will respond with status of all filters that match filter name, channel and id.

### Request

| Type   | Data                             |
| ------ | -------------------------------- |
| `GET_FILTERS_TEST_STATUS` | [GetFiltersTestStatusRequest](./Data-Types#getfiltersteststatusrequest) JSON |

### Response

| Type    | Data                           |
| ------- | ------------------------------ |
| `FILTERS_TEST_STATUS` | dict of \[str, [FiltersData](./Data-Types#filtersdata)\] JSON |

-----------------------------------------------------------------------------------------
## How to Test:
- go to ConnectionTest page
- join as experimenter and as participant
- on experimenter page:
  - press button `GET_FILTERS_DATA` -> should return empty array
  - press button `GET_FILTERS_TEST_STATUS` -> sends response to participant, go to participant page, there should be an answer with empty array
- add `simple_glasses_detection` filter
- on experimenter page:
  - press button `GET_FILTERS_DATA` -> should return array with glasses_detection to true/false
  - press button `GET_FILTERS_TEST_STATUS` -> sends response to participant, go to participant page, there should be an answer similar to `GET_FILTERS_DATA` 

### Optional
- in ConnectionTest.tsx: change api call to backend
  - remove parameters (filter_id, filter_name, etc.)
  - change name of parameters (filter_name -> filter_nane)
- after each change: look if API call still works (need to refresh page or start new connection)
    
example of correct response:
```json
{
    "a": {
        "video": [
            {
                "id": "simple-glasses-detection",
                "data": {
                    "Glasses Detected": false
                }
            }
        ],
        "audio": []
    }
}
```

2023-10-18 13:53 UTC, aykutaaykut commented
It works as expected! Additionally, the filters need to implement the `get_filter_data` function before testing the other filters in the Optional part.

2023-10-18 13:55 UTC, aykutaaykut commented on backend/hub/track_handler.py
> +        filters_data: list[FilterDataDict] = []
I like the type definition, I think it helps a lot to understand the code!

2023-10-18 14:36 UTC, aykutaaykut requested changes
It is a very well-structured PR and clean code!

Only thing was unclear for me that the name of the endpoints. I wouldn't expect the `GET_FILTERS_TEST_STATUS` endpoint to gather filter data and send it to the participants. Therefore, the naming of the endpoint could be improved.

2023-10-18 14:39 UTC, aykutaaykut commented
If the `GET_FILTERS_DATA ` endpoint is called from a participant, it blocks all the endpoint calls both from the experimenter and a participant; therefore I believe this should be addressed before merging. I tried to elaborate on this more in my review.

2023-10-18 14:39 UTC, tobifb commented on frontend/src/modals/ParticipantDataModal/ParticipantDataModal.tsx
> -              .pop()
We are now using `find` instead of `filter`, which returns the first occurence.

2023-10-18 14:41 UTC, tobifb commented on backend/users/participant.py
> +        self.on_message("GET_FILTERS_DATA", self._handle_get_filters_data)
That is a valid point. My idea was to leave the call there, so in future, this can be solved. , I would leave it there, I also made

2023-10-18 14:43 UTC, tobifb commented on backend/filters/filter.py
> +    def toJson(self) -> str:
Yes that is left-over for a previous case which got eliminated. I will remove it.

2023-10-18 14:50 UTC, aykutaaykut commented on backend/users/participant.py
> +        self.on_message("GET_FILTERS_DATA", self._handle_get_filters_data)
Ah I see, yeah that makes sense but maybe commenting out the line `self.on_message("GET_FILTERS_DATA", self._handle_get_filters_data)` with a comment about the problem would be better?

2023-10-18 18:37 UTC, tobifb commented
> Only thing was unclear for me that the name of the endpoints. I wouldn't expect the `GET_FILTERS_TEST_STATUS` endpoint to gather filter data and send it to the participants. Therefore, the naming of the endpoint could be improved.

What about `SEND_FILTERS_TEST_STATUS`?

2023-10-19 11:41 UTC, aykutaaykut requested changes
I followed the steps in the description and it works as expected on the ConnectionTest page

2023-10-19 11:41 UTC, aykutaaykut commented on frontend/src/App.js
> +    connection.api.on("FILTERS_DATA", handleFiltersTestStatus);
For consistency, this function could be renamed e.g. `handleFiltersData`

2023-10-19 11:41 UTC, aykutaaykut commented on frontend/src/pages/ConnectionTest/ConnectionTest.tsx
> +    props.connection.api.on("FILTERS_DATA", handleFiltersData);
This line is the same as line 235, is there a possibility for a typo? Could one of them be `props.connection.api.on("GET_FILTERS_DATA", handleGetFiltersData);`?

2023-10-20 10:24 UTC, VanessaVanessaC approved these changes
It works for glass-detection in Connection Test Page. Maybe add in the Wiki that the API call only returns a non empty object when the filter implements the `get_filter_data` method.

2023-11-23 09:41 UTC, merged