fixed bug in the participant invite link generation
TUMFARSynchrony/experimental-hub pull request #68
Opened 2023-07-04 15:51 UTC by aykutaaykut

This PR solves the bug in the participant invite link by removing the extra "/" character after the endpoint.

2023-07-05 14:07 UTC, mertyldrr approved these changes

2023-07-06 07:12 UTC, NCEghtebas requested changes
Let's resove comments in discord before merge

2023-07-11 14:42 UTC, aykutaaykut commented
I went through the comments on Discord to reproduce the extra "/" error but it didn't happen for me. @NCEghtebas could we have a session to look at it together when you are available?

2023-07-12 17:36 UTC, NCEghtebas approved these changes

2023-07-13 17:26 UTC, merged